frontend: 
	bash components/frontend.sh;
user: 
	bash components/user.sh;
cart: 
	bash components/cart.sh;
catalogue: 
	bash components/catalogue.sh;
dispatch: 
	bash components/dispatch.sh;
mongodb: 
	bash components/mongodb.sh;
mysql: 
	bash components/mysql.sh;
payment: 
	bash components/payment.sh;
rabbitmq:
	bash components/rabbitmq.sh;
redis:
	bash components/redis.sh;
shipping:
	bash components/shipping.sh;
