pipeline {
    agent any
    environment {
        ENV_URL = "Google.com"
        ACCESS_KEY = credentials('AWS_ACCESS_KEY')
        SSH_CRED = credentials('SSH_CRED')
    }
    triggers {pollSCM{30 15 11 5 * }}
    options {
        buildDiscarder(logRotator(numToKeepStr: '3'))
        disableConcurrentBuilds()
        timeout(time: 2, unit: 'MINUTES')
    }
    parameters {
        string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
        text(name: 'BIOGRAPHY', defaultValue: '', description: 'Enter some information about the person')
        booleanParam(name: 'TOGGLE', defaultValue: true, description: 'Toggle this value')
        choice(name: 'CHOICE', choices: ['One', 'Two', 'Three'], description: 'Pick something')
        password(name: 'PASSWORD', defaultValue: 'SECRET', description: 'Enter a password')
    }
    stages {
        stage("Stage One") {
            steps {
                sh "echo One"
                sh "sleep 10"
            }
        }
        stage("Stage Two") {
            steps {
                sh "echo Two"
                sh "echo ENV_URL is ${ENV_URL}"
                sh "echo  AWS_ACCESS_KEY is ${ ACCESS_KEY}"
                sh "echo  SSH_CRED is ${ SSH_CRED}"
                
            }
        }
        stage("Stage Three") {
            environment {
                ENV_URL = "New.Google.com"
            }
            steps {
               sh '''   echo aws
                        echo DevOps
                        echo Bash
                        echo ENV_URL is ${ENV_URL}
                '''
            }
        }
    }
}