pipeline {
    agent any
    stages {
        stage("Stage One") {
            steps {
                sh "echo One"
            }
        }
        stage("Stage Two") {
            steps {
                sh "echo Two"
            }
        }
        stage("Stage Three") {
            steps {
               sh '''   echo aws
                        echo DevOps
                        echo Bash
                '''
            }
        }
    }
}