#!/bin/bash
echo -e "\e[34m I am new COlor\e[0m"
echo -e "\e[36m I am another color\e[0m"
echo -e "\e[35m Which color I am\e[0m"
echo -e "\e[32m I am printing Green Color \e[0m"
echo -e "\e[31m I am printing Red Color \e[0m"
echo -e "\e[33m I am printing Yellow Color \e[0m"
echo -e "\e[34m I am printing Blue Color \e[0m"
echo -e "\e[43;32m I am printing Green Color with YELLOW as Background \e[0m"
echo -e "\e[37;42m this my line ohho \e[0m"
