- name: Demo on facts
  hosts: all
  tasks: 
      - name: print os distribution
        ansible.builtin.debug:
            msg: OS distribution is {{ansible_distribution}}
      - name: print os distribution
        ansible.builtin.debug:
            msg: OS distribution is {{ansible_default_ipv4.macaddress}}



