- name: check xenbus is running or not
  hosts: all
  tasks: 
    - name: check xenbus is running or not
      ansible.builtin.shell: ps -ef | grep xenbus | grep -v grep
      register: out
      ignore_errors: yes
    - name: Print out
      ansible.builtin.debug:
        msg: Start xenbus
    - name: Print out
      ansible.builtin.debug:
        msg: "{{out.stdout}}"