- name: Demo on conditions
  hosts: all
  vars: 
    action: true
    soo: sanjay
  tasks: 
    - name: Runs when os is Centos
      ansible.builtin.debug:
        msg: Hello Sanjay how you doing
      when: action

    - name: Runs when soo is defined
      ansible.builtin.shell: echo "Hellow my name is "{{soo}}""
      when: soo is defined

    - name: Runs when soo is undefined
      ansible.builtin.shell: echo "Hellow my name is bade and bade achhe lagte he"
      when: soo is undefined
      