- name: Set Hostname
  ansible.builtin.include_role:
    name: common
    tasks_from: sethostname 


- name: Configuring {{COMPONENT}}
  ansible.builtin.include_role:
    name: common
    tasks_from: nodejs 
